obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
#Huaqin add for ZQL1650-141 by chenyijun5 at 2018/02/01 start
obj-$(CONFIG_INPUT_STK3321)	+= sensors_class.o stk3x1x/
#Huaqin add for ZQL1650-141 by chenyijun5 at 2018/02/01 end
