#
# for huaqin misc info
#

# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 start
obj-$(CONFIG_HQ_HARDWARE_INFO)   += hardware_info/
# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 end
