obj-$(CONFIG_COMMON_FP)	+= common_X00TD/
obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X00TD/
obj-$(CONFIG_GOODIX_FP)	+= goodix_X00TD/
ifeq ($(CONFIG_MACH_ASUS_X01BD),y)
obj-$(CONFIG_X01BD_CDFINGER_FP)	+= cdfinger_X01BD/
obj-$(CONFIG_X01BD_FOCALTECH_FP)	+= focaltech_X01BD/
endif
