obj-$(CONFIG_COMMON_FP)	+= common/
obj-$(CONFIG_CDFINGER_FP)	+= cdfingerfp/
# Huaqin add for ZQL1650-143 by wangxiang at 2018/02/09 start
obj-$(CONFIG_GOODIX_FP)	+= goodixfp/
# Huaqin add for ZQL1650-143 by wangxiang at 2018/02/09 end
